FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lockb ./bun.lockb
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN echo "DATABASE_URL is: $DATABASE_URL"  # Debugging
RUN env DATABASE_URL=$DATABASE_URL bun run build  # Explicitly set it

EXPOSE 3000

CMD ["bun", "run", "start:web"]